// src/pse-layout.ts

// Wir definieren für jedes Element die Koordinaten im 18x9 Raster
// row: Zeile (1-9), col: Spalte (1-18)
export const elementLayout: Record<string, { row: number, col: number }> = {
    // Periode 1
    "H" : { row: 1, col: 1  },
    "He": { row: 1, col: 18 },

    // Periode 2
    "Li": { row: 2, col: 1  },
    "Be": { row: 2, col: 2  },
    "B" : { row: 2, col: 13 },
    "C" : { row: 2, col: 14 },
    "N" : { row: 2, col: 15 },
    "O" : { row: 2, col: 16 },
    "F" : { row: 2, col: 17 },
    "Ne": { row: 2, col: 18 },

    // Periode 3
    "Na": { row: 3, col: 1  },
    "Mg": { row: 3, col: 2  },
    "Al": { row: 3, col: 13 },
    "Si": { row: 3, col: 14 },
    "P" : { row: 3, col: 15 },
    "S" : { row: 3, col: 16 },
    "Cl": { row: 3, col: 17 },
    "Ar": { row: 3, col: 18 },

    // Periode 4 
    "K" : { row: 4, col: 1  },
    "Ca": { row: 4, col: 2  },
    "Sc": { row: 4, col: 3  },
    "Ti": { row: 4, col: 4  },
    "V" : { row: 4, col: 5  },
    "Cr": { row: 4, col: 6  },
    "Mn": { row: 4, col: 7  },
    "Fe": { row: 4, col: 8  },
    "Co": { row: 4, col: 9  },
    "Ni": { row: 4, col: 10 },
    "Cu": { row: 4, col: 11 },
    "Zn": { row: 4, col: 12 },
    "Ga": { row: 4, col: 13 },
    "Ge": { row: 4, col: 14 },
    "As": { row: 4, col: 15 },
    "Se": { row: 4, col: 16 },
    "Br": { row: 4, col: 17 },
    "Kr": { row: 5, col: 18 },

    
    // Periode 5
    "Rb": { row: 5, col: 1  },
    "Sr": { row: 5, col: 2  },
    "Y" : { row: 5, col: 3  },
    "Zr": { row: 5, col: 4  },
    "Nb": { row: 5, col: 5  },
    "Mo": { row: 5, col: 6  },
    "Tc": { row: 5, col: 7  },
    "Ru": { row: 5, col: 8  },
    "Rh": { row: 5, col: 9  },
    "Pd": { row: 5, col: 10 },
    "Ag": { row: 5, col: 11 },
    "Cd": { row: 5, col: 12 },
    "In": { row: 5, col: 13 },
    "Sn": { row: 5, col: 14 },
    "Sb": { row: 5, col: 15 },
    "Te": { row: 5, col: 16 },
    "I" : { row: 5, col: 17 },
    "Xe": { row: 5, col: 18 },

    //Periode 6
    "Cs": { row: 6, col: 1  },
    "Ba": { row: 6, col: 2  },
    "Lu": { row: 6, col: 3  },
    "Hf": { row: 6, col: 4  },
    "Ta": { row: 6, col: 5  },
    "W" : { row: 6, col: 6  },
    "Re": { row: 6, col: 7  },
    "Os": { row: 6, col: 8  },
    "Ir": { row: 6, col: 9  },
    "Pt": { row: 6, col: 10 },
    "Au": { row: 6, col: 11 },
    "Hg": { row: 6, col: 12 },
    "Tl": { row: 6, col: 13 },
    "Pb": { row: 6, col: 14 },
    "Bi": { row: 6, col: 15 },
    "Po": { row: 6, col: 16 },
    "At": { row: 6, col: 17 },
    "Rn": { row: 6, col: 18 },

    //Periode 7
    "Fr": { row: 7, col: 1  },
    "Ra": { row: 7, col: 2  },
    "Lr": { row: 7, col: 3  },
    "Rf": { row: 7, col: 4  },
    "Db": { row: 7, col: 5  },
    "Sg": { row: 7, col: 6  },
    "Bh": { row: 7, col: 7  },
    "Hs": { row: 7, col: 8  },
    "Mt": { row: 7, col: 9  },
    "Ds": { row: 7, col: 10 },
    "Rg": { row: 7, col: 11 },
    "Cn": { row: 7, col: 12 },
    "Nh": { row: 7, col: 13 },
    "Fl": { row: 7, col: 14 },
    "Mc": { row: 7, col: 15 },
    "Lv": { row: 7, col: 16 },
    "Ts": { row: 7, col: 17 },
    "Og": { row: 7, col: 18 },

    //Lantanoide
    "La": { row: 8, col: 3  },
    "Ce": { row: 8, col: 4  },
    "Pr": { row: 8, col: 5  },
    "Nd": { row: 8, col: 6  },
    "Pm": { row: 8, col: 7  },
    "Sm": { row: 8, col: 8  },
    "Eu": { row: 8, col: 9  },
    "Gd": { row: 8, col: 10 },
    "Tb": { row: 8, col: 11 },
    "Dy": { row: 8, col: 12 },
    "Ho": { row: 8, col: 13 },
    "Er": { row: 8, col: 14 },
    "Tm": { row: 8, col: 15 },
    "Yb": { row: 8, col: 16 },

    //Actenoide
    "Ac": { row: 9, col: 3  },
    "Th": { row: 9, col: 4  },
    "Pa": { row: 9, col: 5  },
    "U" : { row: 9, col: 6  },
    "Np": { row: 9, col: 7  },
    "Pu": { row: 9, col: 8  },
    "Am": { row: 9, col: 9  },
    "Cm": { row: 9, col: 10 },
    "Bk": { row: 9, col: 11 },
    "Cf": { row: 9, col: 12 },
    "Es": { row: 9, col: 13 },
    "Fm": { row: 9, col: 14 },
    "Md": { row: 9, col: 15 },
    "No": { row: 9, col: 16 },

};